apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-kube
  template:
    metadata:
      labels:
        app: spring-boot-kube
    spec:
      containers:
        - name: spring-boot-kube
          image: spring-boot-kube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
